### ISSUE TITLE
[suggestion] make the keybind hold and not toggle

### ISSUE THREAD

**Issue by LiamDun** [ImCodist/quick-menu#1]
would be cool to have an option so that instead of having to press the key twice to both open and close it, once you let go the menu closes and whatever the cursor is on gets activated, similiar to how the gamemode switcher works

**Comment by ImCodist** [comment]
I actually tried to do this at one point but I couldn't quite figure out how to detect for key releases.
But I could totally look into it again!

**Comment by ImCodist** [comment]
Implemented, will be included in the next release! ed69a313d969e5099899523bab194205c818e8ca
