### ISSUE TITLE
[SUGGESTION] Allow for Custom Model Data to be used for icons

### ISSUE THREAD

**Issue by Coswics** [ImCodist/quick-menu#11]
Just a Small QOL thing, but allowing custom model data to be inputted for item appearances in the GUI would be great! since a lot of items dont match icons perfectly (done via resourcepacks)

**Comment by ImCodist** [comment]
I'd be happy to implement this!

**Comment by ImCodist** [comment]
Implemented in commit 3911a6aff13879d0e1a9f5f6f26965dadeebf361.
Can be changed in the advanced options category in the action editor.
