### ISSUE TITLE
[SUGGESTION] Allow for a Custom Amount of Icons Per Row

### ISSUE THREAD

**Issue by Coswics** [ImCodist/quick-menu#12]
![image](https://github.com/ImCodist/quick-menu/assets/142762002/fb37ec5f-1455-4601-888f-e0bce2edd586)
Currently theres no way to configure the amount of horizontal icons/buttons per row and it doesnt scale with the menu width, adding an option for that would be greatly appreciated

**Comment by ImCodist** [comment]
Oh totally!
This is a no brainer I have no idea why I haven't added this!

Will def be included in the next update.

**Comment by ImCodist** [comment]
Implemented in 8da04d2.

**Comment by Coswics** [comment]
getting this in 1.20.1 would be appreciated also ;33

**Comment by ImCodist** [comment]
oh yeah sure, give me like 30 minutes

**Comment by ImCodist** [comment]
here you go!
you can download it [here](https://github.com/ImCodist/quick-menu/releases/tag/v1.2.2), it'll be on modrinth and curseforge shortly!
