### ISSUE TITLE
Allow Curseforge override mods

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ImCodist/quick-menu#15]
If you are not going to support Curseforge, can you add your mod to the [Approved Non-CurseForge Mods](https://docs.google.com/spreadsheets/d/176Wv-PZUo9hFxy6oC6N8tWdquBLPRtSuLbNK-r0_byM/edit#gid=755531188)? You can read about it here: Exporting a Modpack for CurseForge project submission > [Third Party Mods](https://support.curseforge.com/en/support/solutions/articles/9000198500-exporting-a-modpack-for-curseforge-project-submission#Third-Party-Mods). By doing this it will make it easier for modpack devs to include your mod in the overrides folder.
Thank you,
CM

**Comment by ImCodist** [comment]
I've sent in a request.
I'll close this for now and update this issue if something comes of it.

**Comment by ImCodist** [comment]
![image](https://github.com/ImCodist/quick-menu/assets/50346006/1607cf8b-1d58-40ba-a69e-2bbd3e267e0a)
The mod seems to be available on this list now!
