### ISSUE TITLE
New Button Type - Categorie

### ISSUE THREAD

**Issue by DahliaSR** [ImCodist/quick-menu#4]
This is a feature request.
I would love to have the option, to choose from different button types.
The current functionality of the buttons is Command only.

I would love to have the another type of button available.
A Category Button, which allows me to store related actions/commands in an own category.
This would make it alot easier to organize commands.

**Comment by ImCodist** [comment]
I plan on making a different implementation for organizing action buttons in a future update.
But it is not of high priority right now.
