### ISSUE TITLE
Longer Character commands?

### ISSUE THREAD

**Issue by VoidsSpawn** [ImCodist/quick-menu#5]
a lot of commands are cut off so we cant even execute  them sadly

**Comment by ImCodist** [comment]
Sure! I can do that, I wasn't actually quite sure how long I should make the limit. 
Do you have a suggestion as to what I could make the character limit?

**Comment by VoidsSpawn** [comment]
hmmmm. i think 256 since thats the vanilla chat command limit? or longer if possible.

**Comment by ImCodist** [comment]
Solved in commit 7666c82.
May cause issues in the future, I have no idea.
