### ISSUE TITLE
Using modded items as the icon doesn't include the namespace, leading to invalid icons on reload

### ISSUE THREAD

**Issue by Cart3r1234** [ImCodist/quick-menu#7]
I noticed that when using modded items as the icon for an action, restarting the game causes the icon appear blank.  Looking at the config, it seems to not namespace the item with the mod it is from.  This is causing it to try and search for an item with that ID in the minecraft namespace when the config is loaded again, resulting in the blank icon.  Adding the namespace manually to the icon's item in the config file fixes it.  Happens on the latest version.

**Comment by ImCodist** [comment]
Fixed. acff5b0
